### ISSUE TITLE
Get a problem when run ./NetworkLauncher.sh  ,  peers can not start up 

### ISSUE THREAD

**Issue by CocoaWang** [dongmingh/v1Launcher#1]
When I tried to lauch the network ,I got problems with starting peers. 
![wechatimg1](https://cloud.githubusercontent.com/assets/15904918/25269164/0e320480-26ae-11e7-8dd9-f27d8c6deeab.jpeg)

**Comment by dongmingh** [comment]
Do you have fabric and fabric-ca docker images created? and what are their commit levels?
And please provide detail steps on how this occurs, such as networkLauncher command options etc.

**Comment by dongmingh** [comment]
Is the issue resolved? If yes, please close the issue.  Thanks.
